<?php
use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\ClaimController;
use App\Http\Controllers\Api\FavoriteController;
use App\Http\Controllers\Api\ItemController;
use App\Http\Controllers\Api\ConversationController;
use App\Http\Controllers\Api\ProfileController;
use App\Http\Controllers\Api\SafetyController;
use App\Http\Controllers\Api\NotificationController;
use App\Models\Category;
use Illuminate\Support\Facades\Route;
Route::prefix('v1')->group(function () {
    Route::post('auth/register',[AuthController::class,'register']);
    Route::post('auth/login',[AuthController::class,'login']);
    Route::post('auth/forgot-password',[AuthController::class,'forgotPassword']);
    Route::post('auth/reset-password',[AuthController::class,'resetPassword']);
    Route::get('categories',fn()=>response()->json(['success'=>true,'message'=>'Categories retrieved.','data'=>Category::where('is_active',true)->orderBy('name')->get()]));
    Route::get('items',[ItemController::class,'index']); 
    Route::get('items/{item}',[ItemController::class,'show']);
    Route::middleware('auth:sanctum')->group(function () {
        Route::get('auth/me',[AuthController::class,'me']); 
        Route::post('auth/logout',[AuthController::class,'logout']); 
        Route::post('items',[ItemController::class,'store']); 
        Route::get('my-items',[ItemController::class,'mine']);
        Route::get('my-claims',[ClaimController::class,'mine']);
        Route::match(['put','patch'],'items/{item}',[ItemController::class,'update']); 
        Route::delete('items/{item}',[ItemController::class,'destroy']);
        Route::patch('items/{item}/status',[ItemController::class,'changeStatus']);
        Route::get('items/{item}/matches',[ItemController::class,'matches']); 
        Route::get('favorites',[FavoriteController::class,'index']); 
        Route::post('items/{item}/favorite',[FavoriteController::class,'store']); 
        Route::delete('items/{item}/favorite',[FavoriteController::class,'destroy']); 
        Route::post('items/{item}/claims',[ClaimController::class,'store']); 
        Route::get('items/{item}/claims',[ClaimController::class,'index']); 
        Route::patch('claims/{claim}',[ClaimController::class,'review']);
        Route::get('profile',[ProfileController::class,'show']);
        Route::patch('profile',[ProfileController::class,'update']);
        Route::patch('profile/password',[ProfileController::class,'password']);
        Route::post('profile/photo',[ProfileController::class,'photo']);
        Route::delete('profile',[ProfileController::class,'destroy']);
        Route::get('notifications',[NotificationController::class,'index']);
        Route::patch('notifications/read-all',[NotificationController::class,'markAllRead']);
        Route::patch('notifications/{notification}/read',[NotificationController::class,'markRead']);
        Route::get('conversations',[ConversationController::class,'index']);
        Route::post('items/{item}/conversations',[ConversationController::class,'start']);
        Route::get('conversations/{conversation}/messages',[ConversationController::class,'messages']);
        Route::post('conversations/{conversation}/messages',[ConversationController::class,'send']);
        Route::delete('conversations/{conversation}/messages/{message}',[ConversationController::class,'destroyMessage']);
        Route::post('items/{item}/reports',[SafetyController::class,'reportItem']);
        Route::post('users/{user}/reports',[SafetyController::class,'reportUser']);
        Route::post('users/{user}/block',[SafetyController::class,'block']);
    });
});
